- name: creating instances
  hosts: all
  connection: local
  vars:
    sg_id: "sg-0759ad8dc1a8ac235"
    ami_id: "ami-0220d79f3f480ecf5"
    env: "dev"
    domain_name: "learndaws.online"
    instances:
     - mongodb
     - catalogue
  tasks:
   - name: crate ec2 instances
     amazon.aws.ec2_instance:
      name: "{{ item }}-{{ env }}"
      instance_type: t3.micro
      image_id: "{{ ami_id }}"
      region: us-east-1
      security_group: "{{ sg_id }}"
      tags:
       project: roboshop
       name: "{{ item }}-{{ env }} "
       component: "{{ item }}"
       Environment: "{{ env }}"
     loop: "{{ instances }}"
     register: ec2_output 
     when: action == "create" 

   - name:  print ec2_output
     ansible.builtin.debug: 
      msg:  "{{ ec2_output }}"
     when: action == "create"  

   - name: creating r53 with private ip
     amazon.aws.route53:
       state: present
       zone: "{{ domain_name }}"
       record: "{{ item.item }}-{{ env }}.{{ domain_name }}"
       type: A
       ttl: 1
       value: "{{ item.instances[0].private_ip_address }}"
       wait: true  
     loop: "{{ ec2_output.results }}" 
     when: 
      - item.item != "frontend"
      - action == "create" 

   - name: creating r53 with public ip
     amazon.aws.route53:
       state: present
       zone: "{{ domain_name }}"
       record: "roboshop-{{ env }}.{{ domain_name }}"
       type: A
       ttl: 1
       value: "{{ item.instances[0].public_ip_address }}"
       wait: true  
     loop: "{{ ec2_output.results }}" 
     when: 
      - item.item != "frontend"
      - action == "create" 
   #- name: delete ec2 instance
    # amazon.aws.ec2_instance:
     # state: absent
      #name: "{{ item }}-{{ env }} "
    # loop: "{{ instances}}" 

    #1:29 minutes

